server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://k8e205.p.ssafy.io:8761/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: member
          uri: lb://MEMBER
          predicates:
            - Path=/members/signup
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie

        - id: member
          uri: lb://MEMBER
          predicates:
            - Path=/members/index.html

        - id: member
          uri: lb://MEMBER
          predicates:
            - Path=/members/auth/kakao/callback
            - Method=GET

        - id: member
          uri: lb://MEMBER
          predicates:
            - Path=/members/**

        - id: prompts-swagger
          uri: lb://PROMPT
          predicates:
            - Path=/prompts-swagger/**
          filters:
            - SetPath=/{*}
            - SetRequestHeader=crntMemberUuid, myDefaultValue

        - id: prompt
          uri: lb://PROMPT
          predicates:
            - Path=/prompts
            - Method=GET

        - id: prompt
          uri: lb://PROMPT
          predicates:
            - Path=/prompts/**
          filters:
            - AuthorizationHeaderFilter

        - id: search
          uri: lb://SEARCH
          predicates:
            - Path=/search/**

        - id: notice
          uri: lb://NOTICE
          predicates:
            - Path=/notice/**

