server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://zippyziggy.kr:8761/eureka

spring:
  application:
    name: gateway
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://zippyziggy.kr:3000, http://k8e205.p.ssafy.io:3000, http://localhost:3000'
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
      routes:
        - id: member
          uri: lb://MEMBER
          predicates:
            - Path=/members/doc/**
          filters:
            - RewritePath=/members/(?<segment>.*), /$\{segment}

        - id: member
          uri: lb://MEMBER
          predicates:
            - Path=/members/v3/**
          filters:
            - RewritePath=/members/(?<segment>.*), /$\{segment}

        - id: member
          uri: lb://MEMBER
          predicates:
            - Path=/members/signup
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie

        - id: member
          uri: lb://MEMBER
          predicates:
            - Path=/members/index.html

        - id: member
          uri: lb://MEMBER
          predicates:
            - Path=/members/auth/kakao/callback
            - Method=GET

        - id: member
          uri: lb://MEMBER
          predicates:
            - Path=/members/logout
            - Method=POST

        - id: member
          uri: lb://MEMBER
          predicates:
            - Path=/members/**

#          filters:
#            - AuthorizationHeaderFilter


        - id: prompt
          uri: lb://PROMPT
          predicates:
            - Path=/prompts/doc/**
          filters:
            - RewritePath=/prompts/(?<segment>.*), /$\{segment}

        - id: prompt
          uri: lb://PROMPT
          predicates:
            - Path=/prompts/v3/**
          filters:
            - RewritePath=/prompts/(?<segment>.*), /$\{segment}

        - id: prompt
          uri: lb://PROMPT
          predicates:
            - Path=/prompts
            - Method=GET

        - id: prompt
          uri: lb://PROMPT
          predicates:
            - Path=/prompts/{promptUuid}/comments
            - Method=GET

        - id: prompt
          uri: lb://PROMPT
          predicates:
            - Path=/prompts/**
          filters:
           - AuthorizationHeaderFilter

        - id: search
          uri: lb://SEARCH
          predicates:
            - Path=/search/**

        - id: notice
          uri: lb://NOTICE
          predicates:
            - Path=/notice/**

        - id: openapi
          uri: http://zippyziggy.kr:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
            - SetRequestHeader=crntMemberUuid, myDefaultValue

springdoc:
  swagger-ui:
    urls[0]:
      name: prompt
      url: http://zippyziggy.kr:${server.port}/v3/api-docs/prompts
    urls[1]:
      name: member
      url: http://zippyziggy.kr:${server.port}/v3/api-docs/members

