server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://k8e205.p.ssafy.io:8761/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: member
          uri: lb://MEMBER
          predicates:
            - Path=/members/signup
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie

        - id: member
          uri: lb://MEMBER
          predicates:
            - Path=/members/index.html

        - id: member
          uri: lb://MEMBER
          predicates:
            - Path=/members/auth/kakao/callback
            - Method=GET

        - id: member
          uri: lb://MEMBER
          predicates:
            - Path=/members/**

        - id: prompt
          uri: lb://PROMPT
          predicates:
            - Path=/prompts/doc/**
          filters:
            - RewritePath=/prompts/(?<segment>.*), /$\{segment}

        - id: prompt
          uri: lb://PROMPT
          predicates:
            - Path=/prompts/v3/**
          filters:
            - RewritePath=/prompts/(?<segment>.*), /$\{segment}
#            - SetRequestHeader=crntMemberUuid, myDefaultValue

#        - id: prompt
#          uri: lb://PROMPT
#          predicates:
#            - Path=/prompts
#            - Method=GET

        - id: prompt
          uri: lb://PROMPT
          predicates:
            - Path=/prompts/**
          filters:
           - AuthorizationHeaderFilter

        - id: search
          uri: lb://SEARCH
          predicates:
            - Path=/search/**

        - id: notice
          uri: lb://NOTICE
          predicates:
            - Path=/notice/**

        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
            - SetRequestHeader=crntMemberUuid, myDefaultValue

springdoc:
  swagger-ui:
    urls[0]:
      name: prompt
      url: http://localhost:${server.port}/v3/api-docs/prompts
#    urls[1]:
#      name: member
#      url: http://localhost:${server.port}/v3/api-docs/members

