server:
  port: 0

spring:
  application:
    name: prompt
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    hikari:
      max-lifetime: 178000


eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://zippyziggy.kr:8761/eureka

springdoc:
  swagger-ui:
    path: /doc/swagger
    operations-sorter: method

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
