server:
  port: 0

spring:
  application:
    name: prompt
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://k8e205.p.ssafy.io:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh

springfox:
  documentation:
    swagger-ui:
      url: /prompts-swagger/swagger-ui.html