server:
  port: 0

spring:
  application:
    name: notice
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  swagger-ui:
    path: /doc/swagger
    operations-sorter: method

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://k8e205.p.ssafy.io:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
